name: Update CV
on: 
  schedule: 
    - cron: "*/5 * * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v2

      - name: Configurar nombre de usuario y correo electr칩nico
        run: |
          git config --global user.name 'joshtin2505'
          git config --global user.email 'justincastro2505@egmail.com'

      - name: Realizar cambios en el c칩digo
        run: echo "$(date)" >> archivo.txt # Puedes reemplazar esto con cualquier comando para modificar tus archivos

      - name: Commit cambios
        run: |
          git add .
          git commit -m "Commit autom치tico $(date)"
      
      - name: Push cambios
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main