name: Update CV
on: 
  schedule: 
    - cron: "0 */1 * * *"
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install dependencies
      run: pnpm install

    - name: Update CV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pnpm i
        pnpm run update-cv
        
    # - name: Commit files
    #   run: |
    #     git config user.name joshtin2505
    #     git config user.email justincastro2505@gmail.com
    #     git add .
    #     git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update CV with latest info"
    #     git push origin master
