name: Update CV
on: 
  schedule: 
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: # Otorga los permisos para el flujo de trabajo - Esto es necesario para crear un commit
      issues: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Git credentials # Configura las credenciales de Git
        run: |
          git config --global user.name "joshtin2505"
          git config --global user.email "justincastro2505@gmail.com"
          git remote set-url origin https://${{ secrets.YOUR_GITHUB_TOKEN }}@github.com/joshtin2505/minimalist-portafolio.git

      - name: Run script # Ejecuta el script
        run: |
          chmod +x ./.github/scripts/auto_commit.sh
          bash ./.github/scripts/auto_commit.sh